sudo: false
language: python
notifications:
  email:
    recipients:
      - chenjiandongx@qq.com
    on_success: always # default: change
    on_failure: always # default: always
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7
before_install:
  - pip install -r test/requirements.txt
script:
  - python setup.py install
  - make tests
after_success:
  - cd test
  - codecov

