environment:

  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - cd test
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
build: off

test_script:
  - "%PYTHON%/Scripts/nosetests --with-coverage --cover-package pyecharts --cover-package test && cd .. && %PYTHON%/Scripts/flake8 --exclude build --max-line-length 89 --ignore=F401"
